add_newline = false
scan_timeout = 100
command_timeout = 5000

[git_status]
disabled = true

[python]
detect_extensions = []
detect_files = ["pyproject.toml"]
detect_folders = []

[package]
disabled = true

[gcloud]
disabled = true
