name: CI
on:
  push:
    branches: [master, ci]

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Test Installer
        run: apt-get install -y stow make && make stow
